name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy main branch to next.esm.sh
    runs-on: ubuntu-latest
    environment: next

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Run `deploy-ci.sh`
        run: ./scripts/deploy-ci.sh
        env:
          GOOS: linux
          GOARCH: ${{ secrets.DEPLOY_HOST_ARCH }}
          DEPLOY_HOST_NAME: ${{ secrets.DEPLOY_HOST_NAME }}
          DEPLOY_HOST_PORT: ${{ secrets.DEPLOY_HOST_PORT }}
          DEPLOY_SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
