name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test All
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run `go test`
        run: go test ./server ./server/storage -v
        env:
          GO_TEST_S3_ENDPOINT: ${{ secrets.GO_TEST_S3_ENDPOINT }}
          GO_TEST_S3_REGION: ${{ secrets.GO_TEST_S3_REGION }}
          GO_TEST_S3_ACCESS_KEY_ID: ${{ secrets.GO_TEST_S3_ACCESS_KEY_ID }}
          GO_TEST_S3_SECRET_ACCESS_KEY: ${{ secrets.GO_TEST_S3_SECRET_ACCESS_KEY }}

      - name: Run `test/bootstrap.ts`
        run: test/bootstrap.ts -q
